'use strict'

const assert = require('assert/strict')
const fs = require('fs')
const path = require('path')

const flowPath = path.join(__dirname, '..', 'flow', 'cerbo-balancer-controller.json')
const flow = JSON.parse(fs.readFileSync(flowPath, 'utf8'))
const text = fs.readFileSync(flowPath, 'utf8')
assert.ok(flow.some(node => node.id === 'bal-can-reader'))
assert.ok(flow.some(node => node.type === 'victron-input-battery'))
assert.ok(flow.some(node => node.type === 'victron-input-vebus'))
assert.ok(flow.some(node => node.type === 'ui-page' && node.path === '/balancer'))
assert.ok(flow.some(node => node.type === 'ui-page' && node.path === '/balancer-maintenance'))
const maintenanceTemplate = flow.find(node => node.id === 'bal-maintenance')
assert.equal(maintenanceTemplate.templateScope, 'widget:page')
assert.equal(maintenanceTemplate.page, 'bal-maint-page')
assert.equal(maintenanceTemplate.group, '')
assert.equal(maintenanceTemplate.height, 0)
assert.ok(!flow.some(node => node.id === 'bal-maint-group'))
assert.ok(flow.some(node => node.id === 'bal-rs485-read' && node.command.includes('cerbo-balancer-latest.json')))
assert.ok(flow.some(node => node.id === 'bal-rs485-refresh' && node.once === true && node.repeat === '2'))
assert.ok(flow.some(node => node.id === 'bal-maint-tick' && node.repeat === '5'))
assert.ok(flow.some(node => node.id === 'bal-controller'))
assert.ok(flow.filter(node => ['bal-state-persist-delay', 'bal-config-persist-delay'].includes(node.id)).every(node => node.drop === false))
assert.ok(flow.some(node => node.id === 'bal-controls' && node.type === 'ui-template'))
assert.ok(flow.some(node => node.id === 'bal-config-log' && node.filename.includes('cerbo-balancer-config.json')))
assert.ok(flow.some(node => node.id === 'bal-state-load' && node.command.includes('cerbo-balancer-state.json')))
assert.ok(flow.some(node => node.id === 'bal-csv-delete' && node.method === 'post'))
assert.ok(flow.some(node => node.id === 'bal-csv-delete-file' && node.overwriteFile === 'delete'))
assert.ok(text.includes('deleteHref'))
assert.ok(text.includes('deleteFile'))
assert.ok(text.includes('Cerbo battery-monitor selection controls virtual-BMS authority'))
assert.ok(text.includes('can1'))
assert.ok(text.includes('cerbo-balancer-state.json'))
assert.ok(text.includes('effectiveCells'))
assert.ok(text.includes('summedBatteryCurrent'))
assert.ok(text.includes('pendingRemoval'))
assert.ok(text.includes('scanIntervalSeconds'))
assert.ok(text.includes('balancerRs485LastValidSnapshot'))
assert.ok(text.includes('displayState'))
assert.ok(text.includes('Live graphs'))
assert.ok(text.includes('Virtual BMS / DVCC arbitration'))
assert.ok(text.includes('physical authority is selected manually in Cerbo'))
assert.ok(text.includes('activeBms?.label'))
assert.ok(text.includes('Automatic balancing'))
assert.ok(text.includes('set_automatic_balancing'))
assert.ok(text.includes('restore_defaults'))
assert.ok(text.includes('feedForwardGain'))
assert.ok(text.includes('configurationResult'))
assert.ok(text.includes('Discard changes'))
assert.ok(text.includes('authorityState'))
assert.ok(!text.includes('set_mode'))
assert.ok(!text.includes('outputReady'))
assert.ok(!text.includes('manual_start'))
assert.ok(!text.includes('manual_stop'))
assert.ok(!text.includes('set_auto_manual'))
assert.ok(!text.includes('set_enabled'))
assert.ok(!text.includes('Start balancing'))
assert.ok(!text.includes('Stop balancing'))
assert.ok(text.includes('Solar limitation'))
assert.ok(text.includes('Safety CCL'))
assert.ok(text.includes('addressed CID2 61'))
assert.ok(!text.includes('dyness_rs485_service.py'))
assert.ok(!text.includes('victron-output-settings'))
assert.ok(!text.includes('cansend'))
assert.ok(!text.includes('cangen'))
