'use strict'

const assert = require('assert/strict')
const fs = require('fs')
const path = require('path')

const flowPath = path.join(__dirname, '..', 'flow', 'cerbo-balancer-controller.json')
const flow = JSON.parse(fs.readFileSync(flowPath, 'utf8'))
const text = fs.readFileSync(flowPath, 'utf8')
assert.ok(flow.some(node => node.id === 'bal-can-reader'))
assert.ok(flow.some(node => node.type === 'victron-input-battery'))
assert.ok(flow.some(node => node.type === 'victron-input-vebus'))
assert.ok(flow.some(node => node.type === 'ui-page' && node.path === '/balancer'))
assert.ok(flow.some(node => node.type === 'ui-page' && node.path === '/balancer-maintenance'))
assert.ok(flow.some(node => node.id === 'bal-rs485-read' && node.command.includes('cerbo-balancer-latest.json')))
assert.ok(flow.some(node => node.id === 'bal-rs485-refresh' && node.once === true && node.repeat === '2'))
assert.ok(flow.some(node => node.id === 'bal-maint-tick' && node.repeat === '5'))
assert.ok(flow.some(node => node.id === 'bal-controller'))
assert.ok(flow.some(node => node.id === 'bal-controls' && node.type === 'ui-template'))
assert.ok(flow.some(node => node.id === 'bal-config-log' && node.filename.includes('cerbo-balancer-config.json')))
assert.ok(flow.some(node => node.id === 'bal-state-load' && node.command.includes('cerbo-balancer-state.json')))
assert.ok(flow.some(node => node.id === 'bal-csv-delete' && node.method === 'post'))
assert.ok(flow.some(node => node.id === 'bal-csv-delete-file' && node.overwriteFile === 'delete'))
assert.ok(text.includes('deleteHref'))
assert.ok(text.includes('deleteFile'))
assert.ok(text.includes('TEST_MODE'))
assert.ok(text.includes('can1'))
assert.ok(text.includes('cerbo-balancer-state.json'))
assert.ok(text.includes('effectiveCells'))
assert.ok(text.includes('summedBatteryCurrent'))
assert.ok(text.includes('pendingRemoval'))
assert.ok(text.includes('scanIntervalSeconds'))
assert.ok(text.includes('balancerRs485LastValidSnapshot'))
assert.ok(text.includes('displayState'))
assert.ok(text.includes('Live graphs'))
assert.ok(text.includes('Virtual BMS / DVCC arbitration'))
assert.ok(!text.includes('dyness_rs485_service.py'))
assert.ok(!text.includes('victron-output-settings'))
assert.ok(!text.includes('cansend'))
assert.ok(!text.includes('cangen'))
