'use strict'

const assert = require('assert/strict')
const fs = require('fs')
const path = require('path')

const flowPath = path.join(__dirname, '..', 'flow', 'cerbo-balancer-controller.json')
const flow = JSON.parse(fs.readFileSync(flowPath, 'utf8'))
const text = fs.readFileSync(flowPath, 'utf8')
assert.ok(flow.some(node => node.id === 'bal-can-reader'))
assert.ok(flow.some(node => node.type === 'victron-input-battery'))
assert.ok(flow.some(node => node.type === 'victron-input-vebus'))
assert.ok(flow.some(node => node.type === 'ui-page' && node.path === '/balancer'))
assert.ok(flow.some(node => node.type === 'ui-page' && node.path === '/balancer/maintenance'))
assert.ok(flow.some(node => node.id === 'bal-rs485-service' && node.command.includes('--baud 115200')))
assert.ok(flow.some(node => node.id === 'bal-rs485-start' && node.once === true))
assert.ok(flow.some(node => node.id === 'bal-maint-tick' && node.repeat === '5'))
assert.ok(flow.some(node => node.id === 'bal-controller'))
assert.ok(text.includes('TEST_MODE'))
assert.ok(text.includes('can1'))
assert.ok(text.includes('cerbo-balancer-state.json'))
assert.ok(text.includes('effectiveCells'))
assert.ok(text.includes('summedBatteryCurrent'))
assert.ok(!text.includes('victron-output-settings'))
assert.ok(!text.includes('cansend'))
assert.ok(!text.includes('cangen'))
